### ISSUE TITLE
crash 0.2.2

### ISSUE THREAD

**Issue by mosaiyka** [CacahueteSansSel/mcLaunch#37]
How to fix?
[!] mcLaunch v0.2.2 commit aef555d
If you are reporting this, please include this crash report
Platform: Microsoft Windows NT 10.0.22631.0
Platform ID: windows
Java Platform ID: windows-x64
Architecture: x64

Crash Type: Exception

System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\Users\HUAWEI\AppData\Roaming\.mclaunch\system/runtime/java-runtime-gamma/windows-x64/bin/javaw.exe' with working directory 'C:\Users\HUAWEI\AppData\Roaming\.mclaunch\boxes\RvlUUnjH\minecraft'. Не удается найти указанный файл.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at mcLaunch.Launchsite.Core.Minecraft.Run() in /home/cacahuete/Source/Projets/mcLaunch/mcLaunch.Launchsite/Core/Minecraft.cs:line 207
   at mcLaunch.Core.Boxes.Box.Run() in /home/cacahuete/Source/Projets/mcLaunch/mcLaunch.Core/Boxes/Box.cs:line 772
   at mcLaunch.Views.Pages.BoxDetailsPage.RunAsync(String serverAddress, String serverPort, MinecraftWorld world) in /home/cacahuete/Source/Projets/mcLaunch/mcLaunch/Views/Pages/BoxDetailsPage.axaml.cs:line 189
   at mcLaunch.Views.Pages.BoxDetailsPage.Run(String serverAddress, String serverPort, MinecraftWorld world) in /home/cacahuete/Source/Projets/mcLaunch/mcLaunch/Views/Pages/BoxDetailsPage.axaml.cs:line 158
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   at mcLaunch.Program.Main(String[] args) in /home/cacahuete/Source/Projets/mcLaunch/mcLaunch/Program.cs:line 32

**Comment by CacahueteSansSel** [comment]
I'm trying to investigate the issue and will try to reproduce it.
It seems to be a weird path issue, as in the stacktrace there isn't any slash between Roaming and .mcLaunch on the paths.
I'm seeing the code that is responsible for that, and this issue shouldn't be possible, but I'll investigate further.
