### ISSUE TITLE
Crash when installing multiple optional mods along a mod in a box

### ISSUE THREAD

**Issue by CacahueteSansSel** [CacahueteSansSel/mcLaunch#43]
[!] mcLaunch v0.2.3 commit 202bc1a on branch main
If you are reporting this, please include this crash report
Platform: Microsoft Windows NT 10.0.22631.0
Platform ID: windows
Java Platform ID: windows-x64
Architecture: x64
Dotnet version: 8.0.6
System language: French (France) [fr-FR]

Crash Type: Exception

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at mcLaunch.Views.Pages.ContentDetailsPage.<>c__DisplayClass13_0.<<InstallContentFromVersion>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   at mcLaunch.Program.Main(String[] args) in /home/runner/work/mcLaunch/mcLaunch/mcLaunch/Program.cs:line 32

**Comment by CacahueteSansSel** [comment]
Fixed by 00ba1f2
